name: apegen
channels:
  - conda-forge
  - salilab
  - bioconda
dependencies:
  - python=3.11
  - pdbfixer
  - numpy
  - openmm
  - modeller 
  - pymol-open-source
  - biopandas
  - biopython
  - mgltools
  - openmmforcefields
  - python-constraint
  - scikit-learn
  - tabulate
  - pdb-tools 